/*
 * This source file was generated by the Gradle 'init' task
 */
package encryption.decryption;

public class Main {
    
    public static void main(String[] args) {
        UserInterface userInterface = new UserInterface();
        userInterface.run();
    }
}
